accountmailsender:
  protocol: smtps
  host: 465
  username: tcwxx@163.com
  password: TC198808221
  java-mail-properties:
    mail.smtps.auth: true
    system-email: tcwangxiaoxi@163.com 

wxx: 123
   